"""implement relationships

Revision ID: 610c46435be9
Revises: fc1a3fb09c18
Create Date: 2023-12-14 10:28:32.829962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '610c46435be9'
down_revision = 'fc1a3fb09c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities_table'))
    )
    op.create_table('campers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campers_table'))
    )
    op.drop_table('activities')
    op.drop_table('campers')
    op.add_column('signups', sa.Column('camper_id', sa.Integer(), nullable=False))
    op.add_column('signups', sa.Column('activity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_signups_camper_id_campers_table'), 'signups', 'campers_table', ['camper_id'], ['id'])
    op.create_foreign_key(op.f('fk_signups_activity_id_activities_table'), 'signups', 'activities_table', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_signups_activity_id_activities_table'), 'signups', type_='foreignkey')
    op.drop_constraint(op.f('fk_signups_camper_id_campers_table'), 'signups', type_='foreignkey')
    op.drop_column('signups', 'activity_id')
    op.drop_column('signups', 'camper_id')
    op.create_table('campers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_campers')
    )
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_activities')
    )
    op.drop_table('campers_table')
    op.drop_table('activities_table')
    # ### end Alembic commands ###
